---
extends: default
rules:
  document-start: disable
  line-length:
    max: 300
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
  colons:
    max-spaces-before: 0
    max-spaces-after: -1
  comments:
    min-spaces-from-content: 1
  braces:
    forbid: false
